server:
  port: 8080
  servlet:
    context-path: /

  tomcat:
    uri-encoding: utf-8


# mybatis
mybatis:
  type-aliases-package: com.test.springboot.entity
  mapper-locations: classpath:com/test/springboot/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000

spring:
  # thymeleaf
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates
    suffix: .html
    mode: HTML5
  # druid
  datasource:
    url: jdbc:mysql://192.168.31.238:3306/testdb?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 2
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20